# Generated by Django 4.2.19 on 2025-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1500)),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('picture', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
