# Generated by Django 4.2.19 on 2025-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='text_en',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='text_nl',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='title_nl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
