# Generated by Django 4.2.19 on 2025-02-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_tag_blogarticle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
