# Generated by Django 4.2.19 on 2025-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_blogarticle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='summary',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='text',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='text_en',
            field=models.TextField(max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='text_nl',
            field=models.TextField(max_length=15000, null=True),
        ),
    ]
