# Generated by Django 4.2.19 on 2025-02-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_blogarticle_summary_alter_blogarticle_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='summary_en',
            field=models.TextField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='summary_nl',
            field=models.TextField(default='', max_length=150, null=True),
        ),
    ]
