# Generated by Django 4.2.19 on 2025-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_skills', '0002_category_name_en_category_name_nl_skill_skill_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_nl',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
