# Generated by Django 5.1.2 on 2025-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="media/")),
                ("company", models.CharField(default=None, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                ("description_nl", models.TextField(max_length=1000, null=True)),
                ("description_en", models.TextField(max_length=1000, null=True)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "Propaedeutic_exam_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("degree_date", models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
