# Generated by Django 5.1.6 on 2025-02-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_educatione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationexperience',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
