# Generated by Django 4.2.19 on 2025-02-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_educatione', '0002_educationexperience_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationexperience',
            old_name='Propaedeutic_exam_date',
            new_name='propaedeutic_exam_date',
        ),
    ]
