# Generated by Django 5.1.2 on 2025-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                ("photo", models.ImageField(upload_to="media/")),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=250)),
                ("phone_number", models.CharField(default=None, max_length=50)),
                ("email_address", models.EmailField(max_length=254)),
                ("github", models.CharField(max_length=250)),
                ("linkedIn", models.CharField(max_length=250)),
                ("about_me", models.TextField(max_length=1500)),
                ("about_me_en", models.TextField(max_length=1500, null=True)),
                ("about_me_nl", models.TextField(max_length=1500, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]