<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-02-07 18:36
=======
# Generated by Django 5.1.6 on 2025-02-07 10:07
>>>>>>> 275580d7de757fb1a684c2646211044f8392f36a

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="media/")),
                ("gitHubUrl", models.CharField(default=None, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=100)),
                ('gitHubUrl', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('description_nl', models.TextField(max_length=1000, null=True)),
                ('description_en', models.TextField(max_length=1000, null=True)),
>>>>>>> 275580d7de757fb1a684c2646211044f8392f36a
            ],
        ),
    ]
