# Generated by Django 4.2.19 on 2025-04-03 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('document', models.FileField(db_index=True, help_text='Upload your CV!', upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('image', models.ImageField(help_text='Choose a picture for the landingpage', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('title', models.CharField(help_text='Title', max_length=500)),
                ('subtitle', models.CharField(help_text='Subtitle', max_length=500)),
                ('subtitle_nl', models.CharField(help_text='Subtitle', max_length=500, null=True)),
                ('subtitle_en', models.CharField(help_text='Subtitle', max_length=500, null=True)),
                ('about', models.TextField(help_text='About', max_length=2500)),
                ('about_nl', models.TextField(help_text='About', max_length=2500, null=True)),
                ('about_en', models.TextField(help_text='About', max_length=2500, null=True)),
                ('gitHub_url', models.CharField(help_text='Github_url', max_length=500)),
                ('linkedin_url', models.CharField(help_text='LinkedIn url', max_length=500)),
                ('email', models.EmailField(help_text='How can people reach you?', max_length=254)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_landingpage.document')),
                ('cv_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_landingpage.document')),
                ('cv_nl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_landingpage.document')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_landingpage.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
